version: "3.8"
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: dev
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5435:5432
    restart: on-failure:3

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - redis-network

  smtp-server:
    image: namshi/smtp:latest
    ports:
      - 1025:1025
    volumes:
      - ./smtp-server/config.json:/app/config/config.json

volumes:
  redis:
  redis-config:

networks:
  redis-network:
    driver: bridge
